name: radio-deploy-default

include:
  - path: ../radio-registry/docker-compose.yml
  - path: ../radio-analytics/docker-compose.yml

networks:
  radio-net:
    driver: bridge

services:
  radio-registry:
    ports:
      - "8080:8080"

  radio-analytics:
    ports:
      - "8081:8081"