name: radio-deploy-prod

include:
  - path: ../radio-registry/docker-compose.prod.yml
    env_file: ../radio-registry/.env.prod
  - path: ../radio-analytics/docker-compose.prod.yml
    env_file: ../radio-analytics/.env.prod

networks:
  radio-net:
    driver: bridge

services:
  radio-registry:
    ports:
      - "8443:8443"

  radio-analytics:
    ports:
      - "8081:8081"

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - radio-net

volumes:
  kafka-data:
    name: radio-kafka-data